name: Agachaire
main: de.gnmyt.mcdash.MinecraftDashboard
version: 1-21-6-v1
api-version: 1.21
description: Agachaire is a simple dashboard for your Minecraft server (fork of MCDash).
author: Valorium
commands:
  panel:
    description: Changes the password of the current user
    aliases: [password, passwd]
    permission: mcdash.use
